# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: uber/cadence/api/v1/error.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='uber/cadence/api/v1/error.proto',
  package='uber.cadence.api.v1',
  syntax='proto3',
  serialized_options=b'\n\027com.uber.cadence.api.v1B\010ApiProtoP\001Z/github.com/uber/cadence/.gen/proto/api/v1;apiv1',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1fuber/cadence/api/v1/error.proto\x12\x13uber.cadence.api.v1\"P\n$WorkflowExecutionAlreadyStartedError\x12\x18\n\x10start_request_id\x18\x01 \x01(\t\x12\x0e\n\x06run_id\x18\x02 \x01(\t\"G\n\x14\x45ntityNotExistsError\x12\x17\n\x0f\x63urrent_cluster\x18\x01 \x01(\t\x12\x16\n\x0e\x61\x63tive_cluster\x18\x02 \x01(\t\"(\n&WorkflowExecutionAlreadyCompletedError\"W\n\x14\x44omainNotActiveError\x12\x0e\n\x06\x64omain\x18\x01 \x01(\t\x12\x17\n\x0f\x63urrent_cluster\x18\x02 \x01(\t\x12\x16\n\x0e\x61\x63tive_cluster\x18\x03 \x01(\t\"j\n\x1e\x43lientVersionNotSupportedError\x12\x17\n\x0f\x66\x65\x61ture_version\x18\x01 \x01(\t\x12\x13\n\x0b\x63lient_impl\x18\x02 \x01(\t\x12\x1a\n\x12supported_versions\x18\x03 \x01(\t\".\n\x16\x46\x65\x61tureNotEnabledError\x12\x14\n\x0c\x66\x65\x61ture_flag\x18\x01 \x01(\t\"#\n!CancellationAlreadyRequestedError\"\x1a\n\x18\x44omainAlreadyExistsError\"\x14\n\x12LimitExceededError\"\x12\n\x10QueryFailedError\"\x12\n\x10ServiceBusyErrorBV\n\x17\x63om.uber.cadence.api.v1B\x08\x41piProtoP\x01Z/github.com/uber/cadence/.gen/proto/api/v1;apiv1b\x06proto3'
)




_WORKFLOWEXECUTIONALREADYSTARTEDERROR = _descriptor.Descriptor(
  name='WorkflowExecutionAlreadyStartedError',
  full_name='uber.cadence.api.v1.WorkflowExecutionAlreadyStartedError',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='start_request_id', full_name='uber.cadence.api.v1.WorkflowExecutionAlreadyStartedError.start_request_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='run_id', full_name='uber.cadence.api.v1.WorkflowExecutionAlreadyStartedError.run_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=136,
)


_ENTITYNOTEXISTSERROR = _descriptor.Descriptor(
  name='EntityNotExistsError',
  full_name='uber.cadence.api.v1.EntityNotExistsError',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='current_cluster', full_name='uber.cadence.api.v1.EntityNotExistsError.current_cluster', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='active_cluster', full_name='uber.cadence.api.v1.EntityNotExistsError.active_cluster', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=138,
  serialized_end=209,
)


_WORKFLOWEXECUTIONALREADYCOMPLETEDERROR = _descriptor.Descriptor(
  name='WorkflowExecutionAlreadyCompletedError',
  full_name='uber.cadence.api.v1.WorkflowExecutionAlreadyCompletedError',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=211,
  serialized_end=251,
)


_DOMAINNOTACTIVEERROR = _descriptor.Descriptor(
  name='DomainNotActiveError',
  full_name='uber.cadence.api.v1.DomainNotActiveError',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='domain', full_name='uber.cadence.api.v1.DomainNotActiveError.domain', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='current_cluster', full_name='uber.cadence.api.v1.DomainNotActiveError.current_cluster', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='active_cluster', full_name='uber.cadence.api.v1.DomainNotActiveError.active_cluster', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=253,
  serialized_end=340,
)


_CLIENTVERSIONNOTSUPPORTEDERROR = _descriptor.Descriptor(
  name='ClientVersionNotSupportedError',
  full_name='uber.cadence.api.v1.ClientVersionNotSupportedError',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='feature_version', full_name='uber.cadence.api.v1.ClientVersionNotSupportedError.feature_version', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='client_impl', full_name='uber.cadence.api.v1.ClientVersionNotSupportedError.client_impl', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='supported_versions', full_name='uber.cadence.api.v1.ClientVersionNotSupportedError.supported_versions', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=342,
  serialized_end=448,
)


_FEATURENOTENABLEDERROR = _descriptor.Descriptor(
  name='FeatureNotEnabledError',
  full_name='uber.cadence.api.v1.FeatureNotEnabledError',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='feature_flag', full_name='uber.cadence.api.v1.FeatureNotEnabledError.feature_flag', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=450,
  serialized_end=496,
)


_CANCELLATIONALREADYREQUESTEDERROR = _descriptor.Descriptor(
  name='CancellationAlreadyRequestedError',
  full_name='uber.cadence.api.v1.CancellationAlreadyRequestedError',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=498,
  serialized_end=533,
)


_DOMAINALREADYEXISTSERROR = _descriptor.Descriptor(
  name='DomainAlreadyExistsError',
  full_name='uber.cadence.api.v1.DomainAlreadyExistsError',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=535,
  serialized_end=561,
)


_LIMITEXCEEDEDERROR = _descriptor.Descriptor(
  name='LimitExceededError',
  full_name='uber.cadence.api.v1.LimitExceededError',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=563,
  serialized_end=583,
)


_QUERYFAILEDERROR = _descriptor.Descriptor(
  name='QueryFailedError',
  full_name='uber.cadence.api.v1.QueryFailedError',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=585,
  serialized_end=603,
)


_SERVICEBUSYERROR = _descriptor.Descriptor(
  name='ServiceBusyError',
  full_name='uber.cadence.api.v1.ServiceBusyError',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=605,
  serialized_end=623,
)

DESCRIPTOR.message_types_by_name['WorkflowExecutionAlreadyStartedError'] = _WORKFLOWEXECUTIONALREADYSTARTEDERROR
DESCRIPTOR.message_types_by_name['EntityNotExistsError'] = _ENTITYNOTEXISTSERROR
DESCRIPTOR.message_types_by_name['WorkflowExecutionAlreadyCompletedError'] = _WORKFLOWEXECUTIONALREADYCOMPLETEDERROR
DESCRIPTOR.message_types_by_name['DomainNotActiveError'] = _DOMAINNOTACTIVEERROR
DESCRIPTOR.message_types_by_name['ClientVersionNotSupportedError'] = _CLIENTVERSIONNOTSUPPORTEDERROR
DESCRIPTOR.message_types_by_name['FeatureNotEnabledError'] = _FEATURENOTENABLEDERROR
DESCRIPTOR.message_types_by_name['CancellationAlreadyRequestedError'] = _CANCELLATIONALREADYREQUESTEDERROR
DESCRIPTOR.message_types_by_name['DomainAlreadyExistsError'] = _DOMAINALREADYEXISTSERROR
DESCRIPTOR.message_types_by_name['LimitExceededError'] = _LIMITEXCEEDEDERROR
DESCRIPTOR.message_types_by_name['QueryFailedError'] = _QUERYFAILEDERROR
DESCRIPTOR.message_types_by_name['ServiceBusyError'] = _SERVICEBUSYERROR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WorkflowExecutionAlreadyStartedError = _reflection.GeneratedProtocolMessageType('WorkflowExecutionAlreadyStartedError', (_message.Message,), {
  'DESCRIPTOR' : _WORKFLOWEXECUTIONALREADYSTARTEDERROR,
  '__module__' : 'uber.cadence.api.v1.error_pb2'
  # @@protoc_insertion_point(class_scope:uber.cadence.api.v1.WorkflowExecutionAlreadyStartedError)
  })
_sym_db.RegisterMessage(WorkflowExecutionAlreadyStartedError)

EntityNotExistsError = _reflection.GeneratedProtocolMessageType('EntityNotExistsError', (_message.Message,), {
  'DESCRIPTOR' : _ENTITYNOTEXISTSERROR,
  '__module__' : 'uber.cadence.api.v1.error_pb2'
  # @@protoc_insertion_point(class_scope:uber.cadence.api.v1.EntityNotExistsError)
  })
_sym_db.RegisterMessage(EntityNotExistsError)

WorkflowExecutionAlreadyCompletedError = _reflection.GeneratedProtocolMessageType('WorkflowExecutionAlreadyCompletedError', (_message.Message,), {
  'DESCRIPTOR' : _WORKFLOWEXECUTIONALREADYCOMPLETEDERROR,
  '__module__' : 'uber.cadence.api.v1.error_pb2'
  # @@protoc_insertion_point(class_scope:uber.cadence.api.v1.WorkflowExecutionAlreadyCompletedError)
  })
_sym_db.RegisterMessage(WorkflowExecutionAlreadyCompletedError)

DomainNotActiveError = _reflection.GeneratedProtocolMessageType('DomainNotActiveError', (_message.Message,), {
  'DESCRIPTOR' : _DOMAINNOTACTIVEERROR,
  '__module__' : 'uber.cadence.api.v1.error_pb2'
  # @@protoc_insertion_point(class_scope:uber.cadence.api.v1.DomainNotActiveError)
  })
_sym_db.RegisterMessage(DomainNotActiveError)

ClientVersionNotSupportedError = _reflection.GeneratedProtocolMessageType('ClientVersionNotSupportedError', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTVERSIONNOTSUPPORTEDERROR,
  '__module__' : 'uber.cadence.api.v1.error_pb2'
  # @@protoc_insertion_point(class_scope:uber.cadence.api.v1.ClientVersionNotSupportedError)
  })
_sym_db.RegisterMessage(ClientVersionNotSupportedError)

FeatureNotEnabledError = _reflection.GeneratedProtocolMessageType('FeatureNotEnabledError', (_message.Message,), {
  'DESCRIPTOR' : _FEATURENOTENABLEDERROR,
  '__module__' : 'uber.cadence.api.v1.error_pb2'
  # @@protoc_insertion_point(class_scope:uber.cadence.api.v1.FeatureNotEnabledError)
  })
_sym_db.RegisterMessage(FeatureNotEnabledError)

CancellationAlreadyRequestedError = _reflection.GeneratedProtocolMessageType('CancellationAlreadyRequestedError', (_message.Message,), {
  'DESCRIPTOR' : _CANCELLATIONALREADYREQUESTEDERROR,
  '__module__' : 'uber.cadence.api.v1.error_pb2'
  # @@protoc_insertion_point(class_scope:uber.cadence.api.v1.CancellationAlreadyRequestedError)
  })
_sym_db.RegisterMessage(CancellationAlreadyRequestedError)

DomainAlreadyExistsError = _reflection.GeneratedProtocolMessageType('DomainAlreadyExistsError', (_message.Message,), {
  'DESCRIPTOR' : _DOMAINALREADYEXISTSERROR,
  '__module__' : 'uber.cadence.api.v1.error_pb2'
  # @@protoc_insertion_point(class_scope:uber.cadence.api.v1.DomainAlreadyExistsError)
  })
_sym_db.RegisterMessage(DomainAlreadyExistsError)

LimitExceededError = _reflection.GeneratedProtocolMessageType('LimitExceededError', (_message.Message,), {
  'DESCRIPTOR' : _LIMITEXCEEDEDERROR,
  '__module__' : 'uber.cadence.api.v1.error_pb2'
  # @@protoc_insertion_point(class_scope:uber.cadence.api.v1.LimitExceededError)
  })
_sym_db.RegisterMessage(LimitExceededError)

QueryFailedError = _reflection.GeneratedProtocolMessageType('QueryFailedError', (_message.Message,), {
  'DESCRIPTOR' : _QUERYFAILEDERROR,
  '__module__' : 'uber.cadence.api.v1.error_pb2'
  # @@protoc_insertion_point(class_scope:uber.cadence.api.v1.QueryFailedError)
  })
_sym_db.RegisterMessage(QueryFailedError)

ServiceBusyError = _reflection.GeneratedProtocolMessageType('ServiceBusyError', (_message.Message,), {
  'DESCRIPTOR' : _SERVICEBUSYERROR,
  '__module__' : 'uber.cadence.api.v1.error_pb2'
  # @@protoc_insertion_point(class_scope:uber.cadence.api.v1.ServiceBusyError)
  })
_sym_db.RegisterMessage(ServiceBusyError)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
